trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: Release

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '*.sln'
    arguments: '-c $(configuration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'