trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: Release

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.sln'
    arguments: '-c $(configuration)'